### PR TITLE
Fix spot price bug, add method for base addresses

### LINKED ISSUE #20: normalize decimals for calcSpotPricePt()
It's easy to mess up PT spot price calcs for USDC bc it only has 6 decimals and totalSupply has 18.  

image

### PR DESCRIPTION
**Pull request by smmackey**
Fixes a bug in spot price calculation. Without taking into consideration the decimals of precision, our calculation for fixed APR can be way off (specifically for USDC).

Also adds a function to obtain the base token address for a given token. This is necessary to help the Twitter bot parse the addresses json in a much slicker fashion.

Resolves #20

### CODE REVIEW

File: examples/poolDetails.ts [hunk 1]
```diff
@@ -48,7 +49,8 @@ async function main() {
     ptReserves.toString(),
     totalSupply.toString(),
     timeRemainingSeconds,
-    unitSeconds
+    unitSeconds,
+    ptDecimals[0]
```
Comment (jrhea) [inline examples/poolDetails.ts:53]: Here you can't just assume it is the 0 index.  you need to use the ptIndex variable from line 35 above.

File: src/helpers/calcSpotPrice.ts [hunk 2]
```diff
@@ -19,10 +19,16 @@ export function calcSpotPricePt(
   ptReserves: string,
   totalSupply: string,
   timeRemainingSeconds: number,
-  tParamSeconds: number
+  tParamSeconds: number,
+  decimals: number
 ): number {
+  // normalize decimal places of precision to 18
+  const diff = 18 - decimals;
```
Comment (jrhea) [inline src/helpers/calcSpotPrice.ts:26]: maybe just check to make sure that decimals are <= 18

**Review by jrhea — CHANGES_REQUESTED** [review]
this is good....just a couple of things to fix

File: examples/poolDetails.ts (hunk 1 above)
Comment (smmackey) [reply examples/poolDetails.ts]: Okay, that makes sense 😅 Made the edit!

File: src/helpers/calcSpotPrice.ts (hunk 2 above)
Comment (smmackey) [reply src/helpers/calcSpotPrice.ts:30]: Added in a check for that plus a unit test, but let me know if you think there's a better way to handle that error

Comment (jrhea) [reply src/helpers/calcSpotPrice.ts:30]: i think that's good for our purposes.

File: examples/poolDetails.ts [hunk 3]
```diff
@@ -48,7 +49,8 @@ async function main() {
     ptReserves.toString(),
     totalSupply.toString(),
     timeRemainingSeconds,
-    unitSeconds
+    unitSeconds,
+    ptDecimals[ptIndex]
```
Comment (jrhea) [inline examples/poolDetails.ts:53]:
```suggestion
    ptDecimals[baseIndex]
```

File: examples/poolDetails.ts [hunk 4]
```diff
@@ -36,6 +36,7 @@ async function main() {
   let baseIndex = reserves.tokens[0].toLowerCase() == base ? 0 : 1;
   const ptReserves = reserves.balances[ptIndex];
   let baseReserves = reserves.balances[baseIndex];
+  const ptDecimals = reserves.decimals;
```
Comment (jrhea) [inline examples/poolDetails.ts:39]:
```suggestion
  const baseDecimals = reserves.decimals[baseIndex];
```

File: examples/poolDetails.ts (hunk 3 above)
Comment (jrhea) [inline examples/poolDetails.ts:53]:
```suggestion
   baseDecimals
```

**Comment by smmackey** [comment]
tests are passing, gonna give it a merge!
